// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditUserController from "./edit_user_controller"
application.register("edit-user", EditUserController)

import ToastifyController from "./toastify_controller"
application.register("toastify", ToastifyController)

import TweetFormController from "./tweet_form_controller"
application.register("tweet-form", TweetFormController)

import UserNameController from "./user_name_controller"
application.register("user-name", UserNameController)
